export const B2B_CATEGORIES = [
  { slug: 'agricultural-products', nameEn: 'Agricultural Products & Food', icon: '🌾', hsChapters: '01,02,03,04,07,08,09,10,11,12,15,16,17,18,19,20,21,22,23,24', metaDesc: 'Source grains, oilseeds, sunflower oil, sugar, dairy and processed food directly from Ukrainian agricultural producers.' },
  { slug: 'metals-steel', nameEn: 'Metals & Steel', icon: '⚙️', hsChapters: '72,73,74,75,76,78,79,80,81', metaDesc: 'Buy hot-rolled coils, rebars, wire rod, steel pipes and non-ferrous metals from Ukrainian mills.' },
  { slug: 'chemicals-fertilizers', nameEn: 'Chemicals & Fertilizers', icon: '🧪', hsChapters: '28,29,31,32,33,34,38,39', metaDesc: 'Wholesale urea, ammonium nitrate, NPK fertilizers, industrial chemicals from Ukrainian producers.' },
  { slug: 'textiles-apparel', nameEn: 'Textiles & Apparel', icon: '👗', hsChapters: '50,51,52,53,54,55,56,57,58,59,60,61,62,63', metaDesc: 'OEM/ODM clothing, fabrics, workwear, knitwear from certified Ukrainian garment manufacturers.' },
  { slug: 'machinery-equipment', nameEn: 'Machinery & Equipment', icon: '🔧', hsChapters: '84,85,86,87,88,89', metaDesc: 'Industrial machinery, agricultural equipment, engines, and electrical equipment from Ukraine.' },
  { slug: 'wood-paper', nameEn: 'Wood, Timber & Paper', icon: '🌲', hsChapters: '44,45,46,47,48,49', metaDesc: 'Sawn timber, lumber, plywood, MDF, paper and cardboard from Ukrainian wood processing plants.' },
  { slug: 'construction-materials', nameEn: 'Construction Materials', icon: '🏗️', hsChapters: '25,26,68,69,70', metaDesc: 'Cement, bricks, tiles, glass, stone and construction aggregates from Ukrainian suppliers.' },
  { slug: 'electronics', nameEn: 'Electronics & Electrical', icon: '💡', hsChapters: '85,90,91', metaDesc: 'Electronic components, cables, lighting equipment and electrical goods from Ukraine.' },
  { slug: 'automotive-parts', nameEn: 'Automotive Parts', icon: '🚗', hsChapters: '87,40,73', metaDesc: 'Auto parts, components, tires and accessories manufactured in Ukraine.' },
  { slug: 'energy-fuels', nameEn: 'Energy & Fuels', icon: '⚡', hsChapters: '27', metaDesc: 'Coal, petroleum products, biofuels and energy commodities from Ukrainian suppliers.' },
  { slug: 'healthcare-pharma', nameEn: 'Healthcare & Pharmaceuticals', icon: '💊', hsChapters: '30,38', metaDesc: 'Generic medicines, medical devices, supplements from Ukrainian pharma manufacturers.' },
  { slug: 'packaging', nameEn: 'Packaging & Containers', icon: '📦', hsChapters: '39,40,48,49,73,76', metaDesc: 'Plastic, paper, metal and glass packaging solutions from Ukrainian manufacturers.' },
  { slug: 'rubber-plastics', nameEn: 'Rubber & Plastics', icon: '🔵', hsChapters: '39,40', metaDesc: 'Plastic products, rubber goods, polymer materials from Ukrainian chemical plants.' },
  { slug: 'animal-feed', nameEn: 'Animal Feed & Pet Food', icon: '🐄', hsChapters: '23', metaDesc: 'Compound feed, sunflower meal, soybean meal and livestock feed from Ukraine.' },
  { slug: 'sunflower-oil', nameEn: 'Sunflower Oil & Oilseeds', icon: '🌻', hsChapters: '12,15', metaDesc: 'Crude and refined sunflower oil, rapeseed oil, soybean oil in bulk from Ukrainian exporters.' },
  { slug: 'grain-cereals', nameEn: 'Grain & Cereals', icon: '🌾', hsChapters: '10,11', metaDesc: 'Wheat, corn, barley, rye, oats in bulk export quantities from Ukrainian grain traders.' },
  { slug: 'furniture-interior', nameEn: 'Furniture & Interior', icon: '🛋️', hsChapters: '44,94', metaDesc: 'Solid wood furniture, MDF cabinets, upholstered goods from Ukrainian furniture makers.' },
  { slug: 'mineral-products', nameEn: 'Minerals & Mining', icon: '💎', hsChapters: '25,26,71', metaDesc: 'Iron ore, coal, limestone, granite, mineral raw materials from Ukrainian mining companies.' },
  { slug: 'defense-security', nameEn: 'Defense & Security Equipment', icon: '🛡️', hsChapters: '93', metaDesc: 'Ballistic protection, tactical gear and security equipment from certified Ukrainian defense manufacturers.' },
  { slug: 'it-software', nameEn: 'IT & Software Services', icon: '💻', hsChapters: '', metaDesc: 'Custom software development, IT outsourcing and tech services from Ukrainian IT companies.' },
  { slug: 'seeds-plants', nameEn: 'Seeds & Planting Material', icon: '🌱', hsChapters: '06,12', metaDesc: 'Certified crop seeds — sunflower, corn, wheat, rapeseed hybrids from Ukrainian agri-biotech.' },
  { slug: 'dairy-eggs', nameEn: 'Dairy Products & Eggs', icon: '🧀', hsChapters: '04', metaDesc: 'Butter, cheese, milk powder, whey protein and eggs from Ukrainian dairy producers.' },
  { slug: 'honey-beekeeping', nameEn: 'Honey & Beekeeping', icon: '🍯', hsChapters: '04', metaDesc: 'Natural honey, beeswax, propolis and bee products. Ukraine is Europe\'s top honey exporter.' },
  { slug: 'ceramics-glass', nameEn: 'Ceramics & Glass', icon: '🏺', hsChapters: '69,70', metaDesc: 'Ceramic tiles, sanitary ware, glass products and technical ceramics from Ukraine.' },
  { slug: 'cosmetics-personal-care', nameEn: 'Cosmetics & Personal Care', icon: '💄', hsChapters: '33', metaDesc: 'Natural cosmetics, essential oils, personal care products from Ukrainian manufacturers.' },
  { slug: 'frozen-foods', nameEn: 'Frozen Foods & IQF', icon: '❄️', hsChapters: '07,08,20', metaDesc: 'IQF frozen vegetables, fruits, berries and ready meals from Ukrainian food processors.' },
  { slug: 'military-equipment', nameEn: 'Military & Tactical Equipment', icon: '🎖️', hsChapters: '93,62,64', metaDesc: 'Tactical clothing, boots, body armor and military-grade equipment from Ukrainian manufacturers.' },
  { slug: 'renewable-energy', nameEn: 'Renewable Energy Equipment', icon: '☀️', hsChapters: '85', metaDesc: 'Solar panels, wind turbine components, biogas equipment from Ukrainian green energy producers.' },
].map((c, i) => ({ ...c, sortOrder: i }));
