export const SEED_HS_CODES = [
  { hsCode: '1001.99.00', descriptionEn: 'Wheat and meslin (common wheat)', descriptionUa: 'Пшениця м\'яка', chapter: '10', mfnRatePct: 20.9, euDcftaRatePct: 0 },
  { hsCode: '1003.90.00', descriptionEn: 'Barley (other than seed)', descriptionUa: 'Ячмінь', chapter: '10', mfnRatePct: 20.9, euDcftaRatePct: 0 },
  { hsCode: '1005.90.00', descriptionEn: 'Maize (corn), other than seed', descriptionUa: 'Кукурудза', chapter: '10', mfnRatePct: 20.9, euDcftaRatePct: 0 },
  { hsCode: '1201.90.00', descriptionEn: 'Soya beans, whether or not broken', descriptionUa: 'Соя-боби', chapter: '12', mfnRatePct: 0, euDcftaRatePct: 0 },
  { hsCode: '1205.10.90', descriptionEn: 'Rape or colza seeds (other)', descriptionUa: 'Насіння ріпаку', chapter: '12', mfnRatePct: 0, euDcftaRatePct: 0 },
  { hsCode: '1512.11.91', descriptionEn: 'Sunflower-seed oil, crude', descriptionUa: 'Олія соняшникова сира', chapter: '15', mfnRatePct: 5.1, euDcftaRatePct: 0 },
  { hsCode: '1512.19.91', descriptionEn: 'Sunflower-seed oil, refined', descriptionUa: 'Олія соняшникова рафінована', chapter: '15', mfnRatePct: 5.1, euDcftaRatePct: 0 },
  { hsCode: '1701.14.10', descriptionEn: 'Cane sugar, raw, for refining', descriptionUa: 'Цукор-сирець', chapter: '17', mfnRatePct: 22.5, euDcftaRatePct: 0 },
  { hsCode: '7208.51.20', descriptionEn: 'Flat-rolled products of iron, hot-rolled, >10mm', descriptionUa: 'Прокат плоский з чорних металів гарячекатаний', chapter: '72', mfnRatePct: 0, euDcftaRatePct: 0 },
  { hsCode: '7213.10.00', descriptionEn: 'Bars and rods, hot-rolled, in irregularly wound coils', descriptionUa: 'Прутки гарячекатані у бухтах', chapter: '72', mfnRatePct: 0, euDcftaRatePct: 0 },
  { hsCode: '6101.20.10', descriptionEn: 'Men\'s overcoats of cotton, knitted', descriptionUa: 'Пальта чоловічі трикотажні з бавовни', chapter: '61', mfnRatePct: 12.0, euDcftaRatePct: 0 },
  { hsCode: '6204.62.31', descriptionEn: 'Women\'s trousers of cotton', descriptionUa: 'Брюки жіночі з бавовни', chapter: '62', mfnRatePct: 12.0, euDcftaRatePct: 0 },
  { hsCode: '8471.30.00', descriptionEn: 'Portable automatic data-processing machines', descriptionUa: 'Портативні ЕОМ', chapter: '84', mfnRatePct: 0, euDcftaRatePct: 0 },
  { hsCode: '8517.12.00', descriptionEn: 'Telephones for cellular networks (smartphones)', descriptionUa: 'Смартфони', chapter: '85', mfnRatePct: 0, euDcftaRatePct: 0 },
  { hsCode: '2204.21.18', descriptionEn: 'Wine of fresh grapes, in containers ≤2L', descriptionUa: 'Вино виноградне у тарі до 2 л', chapter: '22', mfnRatePct: 5.3, euDcftaRatePct: 0 },
  { hsCode: '4407.10.91', descriptionEn: 'Wood sawn/chipped lengthwise, coniferous, >6mm', descriptionUa: 'Деревина пиляна хвойна понад 6 мм', chapter: '44', mfnRatePct: 0, euDcftaRatePct: 0 },
  { hsCode: '3102.10.10', descriptionEn: 'Urea, in aqueous solution', descriptionUa: 'Карбамід у водному розчині', chapter: '31', mfnRatePct: 6.5, euDcftaRatePct: 0 },
  { hsCode: '0302.13.10', descriptionEn: 'Pacific salmon, fresh or chilled', descriptionUa: 'Лосось тихоокеанський, свіжий або охолоджений', chapter: '03', mfnRatePct: 9.6, euDcftaRatePct: 0 },
];

export const SEED_VENDORS = [
  {
    companyNameEn: 'Agro-Lviv LLC',
    companyNameUa: 'ТОВ «Агро-Львів»',
    slug: 'agro-lviv',
    edrpou: '12345678',
    description: 'Leading grain and oilseed exporter from western Ukraine. ISO 9001 certified. Direct contracts with EU buyers since 2015.',
    region: 'Lviv',
    city: 'Lviv',
    yearEstablished: 2008,
    employeeCount: '51-200',
    category: 'food',
    isVerified: true,
    kycStatus: 'approved',
    certifications: [
      { certType: 'ISO9001', certNumber: 'ISO-2024-001' },
      { certType: 'HACCP', certNumber: 'HACCP-2024-042' },
      { certType: 'GlobalGAP', certNumber: 'GGN-4052852045123' },
    ],
    products: [
      { nameEn: 'Sunflower Oil Crude', nameUa: 'Олія соняшникова сира', hsCode: '1512.11.91', unit: 'MT', minOrderQty: 20, priceUsd: 980 },
      { nameEn: 'Wheat (common)', nameUa: 'Пшениця м\'яка', hsCode: '1001.99.00', unit: 'MT', minOrderQty: 500, priceUsd: 220 },
      { nameEn: 'Corn (Maize)', nameUa: 'Кукурудза', hsCode: '1005.90.00', unit: 'MT', minOrderQty: 500, priceUsd: 195 },
    ],
  },
  {
    companyNameEn: 'Metal-Dnipro JSC',
    companyNameUa: 'АТ «Метал-Дніпро»',
    slug: 'metal-dnipro',
    edrpou: '23456789',
    description: 'Steel products manufacturer. Hot-rolled coils, rebars, wire rod. Exporting to 18 countries. ISO 9001 & CE certified.',
    region: 'Dnipropetrovsk',
    city: 'Dnipro',
    yearEstablished: 1995,
    employeeCount: '1000+',
    category: 'metals',
    isVerified: true,
    kycStatus: 'approved',
    certifications: [
      { certType: 'ISO9001', certNumber: 'ISO-2023-887' },
      { certType: 'CE', certNumber: 'CE-2024-0055' },
    ],
    products: [
      { nameEn: 'Hot-rolled coil (HRC)', nameUa: 'Рулон г/к', hsCode: '7208.51.20', unit: 'MT', minOrderQty: 100, priceUsd: 580 },
      { nameEn: 'Rebar B500C', nameUa: 'Арматура B500C', hsCode: '7213.10.00', unit: 'MT', minOrderQty: 50, priceUsd: 620 },
    ],
  },
  {
    companyNameEn: 'Textile-Kharkiv Ltd',
    companyNameUa: 'ТОВ «Текстиль-Харків»',
    slug: 'textile-kharkiv',
    edrpou: '34567890',
    description: 'Garment manufacturer specializing in men\'s and women\'s outerwear. OEM/ODM production. BRC and OEKO-TEX certified.',
    region: 'Kharkiv',
    city: 'Kharkiv',
    yearEstablished: 2001,
    employeeCount: '201-500',
    category: 'textiles',
    isVerified: true,
    kycStatus: 'approved',
    certifications: [
      { certType: 'BRC', certNumber: 'BRC-2024-TX-091' },
      { certType: 'ISO9001', certNumber: 'ISO-2024-TX-011' },
    ],
    products: [
      { nameEn: 'Men\'s Cotton Jacket', nameUa: 'Куртка чоловіча бавовняна', hsCode: '6101.20.10', unit: 'PCS', minOrderQty: 500, priceUsd: 28 },
      { nameEn: 'Women\'s Trousers', nameUa: 'Брюки жіночі', hsCode: '6204.62.31', unit: 'PCS', minOrderQty: 500, priceUsd: 18 },
    ],
  },
  {
    companyNameEn: 'ChemPro Ukraine',
    companyNameUa: 'ХімПро Україна',
    slug: 'chempro-ukraine',
    edrpou: '45678901',
    description: 'Agricultural chemicals and fertilizers. Urea, ammonium nitrate, NPK blends. ISO 14001 environmental certified.',
    region: 'Odesa',
    city: 'Odesa',
    yearEstablished: 2005,
    employeeCount: '51-200',
    category: 'chemicals',
    isVerified: false,
    kycStatus: 'pending',
    certifications: [
      { certType: 'ISO14001', certNumber: 'ISO14-2023-CH-007' },
    ],
    products: [
      { nameEn: 'Urea (aqueous solution)', nameUa: 'Карбамід рідкий', hsCode: '3102.10.10', unit: 'MT', minOrderQty: 20, priceUsd: 310 },
    ],
  },
];
